
services:
  yolo-jupyter:
    build: .
    container_name: aisf_dev_jupyter
    ports:
      - "8080:8080"  # 예비용 포트 (추가 웹 서비스 대비)
      - "8888:8888"  # JupyterLab
    volumes:
      - /c/data1/lx/aisf2:/workspace/data  # Windows 호스트의 C:\data1
    restart: unless-stopped

    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]